# Generated by Django 3.1.1 on 2020-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="dummy@api.dev", max_length=256),
        ),
    ]
