# Generated by Django 3.1.1 on 2020-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                default="dummy@api.dev", max_length=256, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joining_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
