# Generated by Django 3.1.1 on 2020-09-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_usermovies_userpermissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermovies",
            unique_together={("user", "movie")},
        ),
    ]
